### ISSUE TITLE
No LICENSE/COPYING file.

### ISSUE THREAD

**Issue by FieryMewtwo** [pret/pmd-red#81] opened 2021-12-03 17:08 UTC
This means that no one has any rights to pokeemerald, including modifying it, playing it, or even cloning it. We could even write a license from scratch that Nintendo wouldn't be able to yell at us about.

**Comment by aaaaaa123456789** [comment] 2021-12-03 17:11
Duplicate of pret/pokeemerald#1569. It's the same issue.

**Closed** 2021-12-03 17:12 UTC
